# Generated by Django 3.2.11 on 2022-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blogcore.Tag', verbose_name='tags'),
        ),
    ]
